package primero;
// Generated 25-feb-2020 15:22:25 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private String cod;
	private Familia familia;
	private String nombre;
	private String nombreCorto;
	private String descripcion;
	private BigDecimal pvp;
	private Set stocks = new HashSet(0);

	public Producto() {
	}

	public Producto(String cod, Familia familia, String nombreCorto, BigDecimal pvp) {
		this.cod = cod;
		this.familia = familia;
		this.nombreCorto = nombreCorto;
		this.pvp = pvp;
	}

	public Producto(String cod, Familia familia, String nombre, String nombreCorto, String descripcion, BigDecimal pvp,
			Set stocks) {
		this.cod = cod;
		this.familia = familia;
		this.nombre = nombre;
		this.nombreCorto = nombreCorto;
		this.descripcion = descripcion;
		this.pvp = pvp;
		this.stocks = stocks;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombreCorto() {
		return this.nombreCorto;
	}

	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getPvp() {
		return this.pvp;
	}

	public void setPvp(BigDecimal pvp) {
		this.pvp = pvp;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
