package primero;
// Generated 25-feb-2020 15:22:25 by Hibernate Tools 5.2.12.Final

/**
 * StockId generated by hbm2java
 */
public class StockId implements java.io.Serializable {

	private String producto;
	private int tienda;

	public StockId() {
	}

	public StockId(String producto, int tienda) {
		this.producto = producto;
		this.tienda = tienda;
	}

	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public int getTienda() {
		return this.tienda;
	}

	public void setTienda(int tienda) {
		this.tienda = tienda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockId))
			return false;
		StockId castOther = (StockId) other;

		return ((this.getProducto() == castOther.getProducto()) || (this.getProducto() != null
				&& castOther.getProducto() != null && this.getProducto().equals(castOther.getProducto())))
				&& (this.getTienda() == castOther.getTienda());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProducto() == null ? 0 : this.getProducto().hashCode());
		result = 37 * result + this.getTienda();
		return result;
	}

}
