package primero;
// Generated 25-feb-2020 15:22:25 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tienda generated by hbm2java
 */
public class Tienda implements java.io.Serializable {

	private Integer cod;
	private String nombre;
	private String tlf;
	private Set stocks = new HashSet(0);

	public Tienda() {
	}

	public Tienda(String nombre) {
		this.nombre = nombre;
	}

	public Tienda(String nombre, String tlf, Set stocks) {
		this.nombre = nombre;
		this.tlf = tlf;
		this.stocks = stocks;
	}

	public Integer getCod() {
		return this.cod;
	}

	public void setCod(Integer cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
